baseURL = "https://erp12.github.io"
languageCode = "en-us"
title = "ERP"
theme = "beautifulhugo"
publishDir = ".."
sectionPagesMenu = "main"

[params]
  subtitle = "Another developer rambling online."
  author = "Eddie Pantridge"
  logo = "img/logo.png"
