baseURL = "https://erp12.github.io"
languageCode = "en-us"
title = "ERP"
theme = "beautifulhugoERP"
publishDir = ".."
sectionPagesMenu = "main"

[params]
  subtitle = "Another developer rambling online."
  logo = "img/logo.png"

  [Author]
    name = "Eddie Pantridge"
    website = "https://erp12.github.io"
    github = "erp12"
    twitter = "EdEddieEdster"
    # linkedin = "username"
    # stackoverflow = "users/XXXXXXX/username"
    # instagram = "username"
    # youtube = "user/username" # or channel/channelname
